### PR TITLE
obfuscate reverse()

### PR DESCRIPTION
**Pull request by AliAryanTech**
Just testing did I perfectly reverse it, so give me points 10/?

### CODE REVIEW

**Comment by AliAryanTech** [comment]
@SamPandey001 merge pull

**Comment by SamPandey001** [comment]
There is nothing to merge.
Other files were obfuscated so i just did same with that.

**Comment by AliAryanTech** [comment]
> There is nothing to merge. Other files were obfuscated so i just did same with that.

So, I should reverse obfuscate on all file's. I guess that's what you mean 😏

**Comment by SheIITear** [comment]
mm

**Pull request closed without merging**
